import { useEffect, useState } from 'react'
import { Alarm, ArrowLeft, Check, CheckCircle, Clock, Fire, House, ListPlus, Pause, Play, Plus, Trash, TrendUp, X } from '@phosphor-icons/react'
import { AnimatePresence, motion } from 'motion/react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import { create } from 'zustand'
import './styles.css'

type Task = { id: string; title: string; note?: string; primary: boolean; completed: boolean }
type ApiTask = { id: string; title: string; description: string | null; isPrimary: boolean; completed: boolean }
type FormData = { title: string; note: string; primary: boolean }
const schema = z.object({ title: z.string().trim().min(2, 'Escribe al menos 2 caracteres'), note: z.string().optional(), primary: z.boolean() })
const useStore = create<{ focusSessions: number; addSession: () => void }>((set) => ({ focusSessions: 0, addSession: () => set((state) => ({ focusSessions: state.focusSessions + 1 })) }))

const api = async (input: RequestInfo, init?: RequestInit) => { const response = await fetch(input, { ...init, headers: { 'Content-Type': 'application/json', ...init?.headers } }); if (!response.ok) throw new Error('No se pudo conectar con FocusFlow'); return response.status === 204 ? null : response.json() }
const fromApi = (task: ApiTask): Task => ({ id: task.id, title: task.title, note: task.description ?? undefined, primary: task.isPrimary, completed: task.completed })

export default function App() {
  const queryClient = useQueryClient(); const { focusSessions, addSession } = useStore(); const [form, setForm] = useState(false); const [focus, setFocus] = useState<Task | null>(null); const [toast, setToast] = useState('')
  const tasksQuery = useQuery({ queryKey: ['tasks'], queryFn: async () => (await api('/api/tasks') as ApiTask[]).map(fromApi), retry: 1 })
  const tasks = tasksQuery.data ?? []
  const change = useMutation({ mutationFn: ({ id, completed }: { id: string; completed: boolean }) => api(`/api/tasks?id=${id}`, { method: 'PATCH', body: JSON.stringify({ completed }) }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['tasks'] }), onError: () => setToast('No se pudo actualizar') })
  const removeTask = useMutation({ mutationFn: (id: string) => api(`/api/tasks?id=${id}`, { method: 'DELETE' }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['tasks'] }), onError: () => setToast('No se pudo eliminar') })
  const createTask = useMutation({ mutationFn: (data: FormData) => api('/api/tasks', { method: 'POST', body: JSON.stringify({ id: crypto.randomUUID(), title: data.title.trim(), description: data.note.trim() || undefined, isPrimary: data.primary || tasks.length === 0 }) }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['tasks'] }); setForm(false); setToast('Tarea creada') }, onError: () => setToast('No se pudo guardar la tarea') })
  const saveSession = useMutation({ mutationFn: (taskId: string) => api('/api/focus', { method: 'POST', body: JSON.stringify({ id: crypto.randomUUID(), taskId, durationSeconds: 1500 }) }) })
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(''), 2400); return () => window.clearTimeout(timer) }, [toast])
  const completed = tasks.filter((task) => task.completed).length; const primary = tasks.find((task) => task.primary && !task.completed) ?? tasks.find((task) => !task.completed); const percent = tasks.length ? Math.round(completed / tasks.length * 100) : 0
  const toggle = (task: Task) => { change.mutate({ id: task.id, completed: !task.completed }); setToast('Tarea actualizada') }
  const remove = (id: string) => { removeTask.mutate(id); setToast('Tarea eliminada') }
  const add = (data: FormData) => { if (schema.safeParse(data).success) createTask.mutate(data) }
  return <div className="app-shell"><AnimatePresence mode="wait">{focus ? <FocusScreen task={focus} close={() => setFocus(null)} complete={() => { saveSession.mutate(focus.id); change.mutate({ id: focus.id, completed: true }); addSession(); setFocus(null); setToast('Sesión completada · +25 min') }} /> : <motion.div key="home" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
     <header className="topbar"><div className="brand-mark">F</div><div><p className="eyebrow">{new Intl.DateTimeFormat('es-ES', { weekday: 'long', day: '2-digit', month: 'short' }).format(new Date()).toUpperCase()}</p><h1>Buenos días, Alex</h1></div><div className="avatar">A</div></header>
    <main className="content"><section className="hello"><div><span className="lime-dot" /> Tu ritmo de hoy</div><p>Un paso enfocado<br /><em>a la vez.</em></p></section>
      <section className="focus-card"><div className="card-top"><span className="label lime-label"><Fire size={15} weight="fill" /> FOCO PRINCIPAL</span><span className="status-dot">● LISTO</span></div><h2>{primary?.title ?? 'Elige una tarea para empezar'}</h2><p className="muted">{primary?.note ?? 'Crea tu primera tarea y haz que el día avance.'}</p><button className="primary-button" onClick={() => primary ? setFocus(primary) : setForm(true)}><Play size={17} weight="fill" /> Enfocarme 25 min <span>→</span></button></section>
      <section className="timer-strip"><div className="timer-icon"><Clock size={22} /></div><div><strong>Tu próximo bloque</strong><span>25 min de concentración</span></div><span className="ready-pill">POMODORO</span></section>
      <div className="section-heading"><div><span className="eyebrow">LISTA BREVE</span><h3>Tareas de hoy</h3></div><button className="add-link" onClick={() => setForm(true)}><Plus size={18} /> Añadir</button></div>
      <section className="task-list">{tasksQuery.isLoading ? <div className="empty"><Clock size={30} /><strong>Cargando tu enfoque…</strong><span>Estamos buscando tus tareas.</span></div> : tasksQuery.isError ? <div className="empty"><strong>No pudimos cargar tus tareas</strong><span>Revisa la conexión e inténtalo de nuevo.</span><button onClick={() => tasksQuery.refetch()}>Reintentar</button></div> : tasks.length ? tasks.map((task) => <TaskRow key={task.id} task={task} toggle={toggle} remove={remove} />) : <div className="empty"><ListPlus size={30} /><strong>Tu lista está despejada</strong><span>Añade una tarea para comenzar.</span><button onClick={() => setForm(true)}>Crear tarea</button></div>}</section>
     <section className="progress-card" id="progress"><div className="card-top"><div><span className="label">PROGRESO DEL DÍA</span><h3>{percent === 100 ? 'Día completo' : 'Construyendo impulso'}</h3></div><div className="progress-number">{percent}<small>%</small></div></div><div className="progress-track"><motion.div className="progress-fill" animate={{ width: `${percent}%` }} /></div><div className="progress-meta"><span>{completed} de {tasks.length} completadas</span><span><Alarm size={15} /> {focusSessions} sesiones</span></div></section>
    </main><BottomNav />
  </motion.div>}</AnimatePresence>{form && <TaskForm saving={createTask.isPending} close={() => setForm(false)} save={add} />}{toast && <div className="toast" role="status"><CheckCircle size={19} weight="fill" /> {toast}</div>}</div>
}

function TaskRow({ task, toggle, remove }: { task: Task; toggle: (task: Task) => void; remove: (id: string) => void }) { return <motion.div layout className={`task-row ${task.completed ? 'done' : ''}`}><button className="check" onClick={() => toggle(task)} aria-label={`Completar ${task.title}`}>{task.completed && <Check size={15} weight="bold" />}</button><div className="task-copy"><strong>{task.title}</strong>{task.note && <span>{task.note}</span>}</div>{task.primary && !task.completed && <span className="mini-tag">FOCO</span>}<button className="delete-button" onClick={() => remove(task.id)} aria-label="Eliminar tarea"><Trash size={17} /></button></motion.div> }
function TaskForm({ close, save, saving }: { close: () => void; save: (data: FormData) => void; saving: boolean }) { const { register, handleSubmit, formState: { errors } } = useForm<FormData>({ defaultValues: { primary: false, note: '' } }); return <div className="overlay" onMouseDown={close}><motion.form initial={{ y: 35 }} animate={{ y: 0 }} className="sheet" onMouseDown={(event) => event.stopPropagation()} onSubmit={handleSubmit(save)}><div className="sheet-head"><div><span className="eyebrow">NUEVA TAREA</span><h2>¿Qué quieres lograr?</h2></div><button type="button" className="icon-button" onClick={close} aria-label="Cerrar"><X size={21} /></button></div><label>Título<input autoFocus {...register('title')} placeholder="Ej. Leer capítulo 3" />{errors.title && <small className="error">{errors.title.message}</small>}</label><label>Nota <span className="optional">OPCIONAL</span><textarea {...register('note')} placeholder="Un poco de contexto…" /></label><label className="primary-toggle"><input type="checkbox" {...register('primary')} /><span className="toggle"><span /></span> Marcar como foco principal</label><button className="primary-button" disabled={saving} type="submit"><Check size={18} /> {saving ? 'Guardando…' : 'Guardar tarea'}</button></motion.form></div> }
function FocusScreen({ task, close, complete }: { task: Task; close: () => void; complete: () => void }) { const [seconds, setSeconds] = useState(1500); const [running, setRunning] = useState(false); useEffect(() => { if (!running) return; const timer = window.setInterval(() => setSeconds((value) => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer) }, [running]); const time = `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`; const finished = seconds === 0; return <motion.div className="focus-screen" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><button className="close-focus" onClick={close} aria-label="Cerrar"><ArrowLeft size={21} /></button><div className="focus-center"><div className="focus-orbit"><div className="focus-core"><Clock size={27} weight="fill" /></div></div><span className="eyebrow">SESIÓN DE CONCENTRACIÓN</span><div className="big-time">{time}</div><p>{task.title}</p></div><div className="focus-panel"><span className="label">BLOQUE 01 · 25 MINUTOS</span><h2>{finished ? 'Buen trabajo. El bloque terminó.' : 'Tu atención es el espacio.'}</h2><div className="focus-actions"><button className="play-focus" onClick={() => finished ? complete() : setRunning(!running)}>{running ? <Pause size={19} weight="fill" /> : <Play size={19} weight="fill" />} {running ? 'Pausar' : finished ? 'Guardar sesión' : 'Comenzar'}</button><button className="finish-focus" onClick={complete}>Terminar</button></div></div></motion.div> }
function BottomNav() { return <nav className="bottom-nav"><a className="active" href="#"><House size={21} weight="fill" /><span>Hoy</span></a><a href="#progress"><TrendUp size={21} /><span>Resumen</span></a></nav> }
