import { useEffect, useState } from 'react'
import { Alarm, ArrowLeft, Check, CheckCircle, Clock, Fire, House, ListPlus, Pause, Play, Plus, Trash, TrendUp, X } from '@phosphor-icons/react'
import { AnimatePresence, motion } from 'motion/react'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import { create } from 'zustand'
import './styles.css'

type Task = { id: string; title: string; note?: string; primary: boolean; completed: boolean }
type FormData = { title: string; note: string; primary: boolean }
const schema = z.object({ title: z.string().trim().min(2, 'Escribe al menos 2 caracteres'), note: z.string().optional(), primary: z.boolean() })
const initialTasks: Task[] = [
  { id: 'starter-1', title: 'Preparar propuesta del proyecto', note: 'Revisar objetivos y próximos pasos', primary: true, completed: false },
  { id: 'starter-2', title: 'Responder mensajes pendientes', primary: false, completed: false },
  { id: 'starter-3', title: 'Caminar 20 minutos', primary: false, completed: false },
]
function storedTasks() { try { return JSON.parse(localStorage.getItem('focusflow-tasks') ?? 'null') as Task[] ?? initialTasks } catch { return initialTasks } }
const useStore = create<{ tasks: Task[]; setTasks: (tasks: Task[]) => void }>((set) => ({ tasks: storedTasks(), setTasks: (tasks) => set({ tasks }) }))

export default function App() {
  const { tasks, setTasks } = useStore(); const [form, setForm] = useState(false); const [focus, setFocus] = useState<Task | null>(null); const [toast, setToast] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => localStorage.setItem('focusflow-tasks', JSON.stringify(tasks)), [tasks])
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(''), 2400); return () => window.clearTimeout(timer) }, [toast])
  const completed = tasks.filter((task) => task.completed).length; const primary = tasks.find((task) => task.primary && !task.completed) ?? tasks.find((task) => !task.completed); const percent = tasks.length ? Math.round(completed / tasks.length * 100) : 0
  const toggle = (id: string) => { setTasks(tasks.map((task) => task.id === id ? { ...task, completed: !task.completed } : task)); setToast('Tarea actualizada') }
  const remove = (id: string) => { setTasks(tasks.filter((task) => task.id !== id)); setToast('Tarea eliminada') }
  const add = async (data: FormData) => { setSaving(true); const result = schema.safeParse(data); if (!result.success) { setSaving(false); return }; const next: Task = { id: crypto.randomUUID(), title: data.title.trim(), note: data.note.trim(), primary: data.primary || tasks.length === 0, completed: false }; setTasks([...tasks.map((task) => data.primary ? { ...task, primary: false } : task), next]); setSaving(false); setForm(false); setToast('Tarea creada') }
  return <div className="app-shell"><AnimatePresence mode="wait">{focus ? <FocusScreen task={focus} close={() => setFocus(null)} complete={() => { toggle(focus.id); setFocus(null); setToast('Sesión completada · +25 min') }} /> : <motion.div key="home" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
    <header className="topbar"><div className="brand-mark">F</div><div><p className="eyebrow">JUEVES · 13 AGO 2026</p><h1>Buenos días, Alex</h1></div><div className="avatar">A</div></header>
    <main className="content"><section className="hello"><div><span className="lime-dot" /> Tu ritmo de hoy</div><p>Un paso enfocado<br /><em>a la vez.</em></p></section>
      <section className="focus-card"><div className="card-top"><span className="label lime-label"><Fire size={15} weight="fill" /> FOCO PRINCIPAL</span><span className="status-dot">● LISTO</span></div><h2>{primary?.title ?? 'Elige una tarea para empezar'}</h2><p className="muted">{primary?.note ?? 'Crea tu primera tarea y haz que el día avance.'}</p><button className="primary-button" onClick={() => primary ? setFocus(primary) : setForm(true)}><Play size={17} weight="fill" /> Enfocarme 25 min <span>→</span></button></section>
      <section className="timer-strip"><div className="timer-icon"><Clock size={22} /></div><div><strong>Tu próximo bloque</strong><span>25 min de concentración</span></div><span className="ready-pill">POMODORO</span></section>
      <div className="section-heading"><div><span className="eyebrow">LISTA BREVE</span><h3>Tareas de hoy</h3></div><button className="add-link" onClick={() => setForm(true)}><Plus size={18} /> Añadir</button></div>
      <section className="task-list">{tasks.length ? tasks.map((task) => <TaskRow key={task.id} task={task} toggle={toggle} remove={remove} />) : <div className="empty"><ListPlus size={30} /><strong>Tu lista está despejada</strong><span>Añade una tarea para comenzar.</span><button onClick={() => setForm(true)}>Crear tarea</button></div>}</section>
      <section className="progress-card"><div className="card-top"><div><span className="label">PROGRESO DEL DÍA</span><h3>{percent === 100 ? 'Día completo' : 'Construyendo impulso'}</h3></div><div className="progress-number">{percent}<small>%</small></div></div><div className="progress-track"><motion.div className="progress-fill" animate={{ width: `${percent}%` }} /></div><div className="progress-meta"><span>{completed} de {tasks.length} completadas</span><span><Alarm size={15} /> 0 sesiones</span></div></section>
    </main><BottomNav />
  </motion.div>}</AnimatePresence>{form && <TaskForm saving={saving} close={() => setForm(false)} save={add} />}{toast && <div className="toast" role="status"><CheckCircle size={19} weight="fill" /> {toast}</div>}</div>
}

function TaskRow({ task, toggle, remove }: { task: Task; toggle: (id: string) => void; remove: (id: string) => void }) { return <motion.div layout className={`task-row ${task.completed ? 'done' : ''}`}><button className="check" onClick={() => toggle(task.id)} aria-label={`Completar ${task.title}`}>{task.completed && <Check size={15} weight="bold" />}</button><div className="task-copy"><strong>{task.title}</strong>{task.note && <span>{task.note}</span>}</div>{task.primary && !task.completed && <span className="mini-tag">FOCO</span>}<button className="delete-button" onClick={() => remove(task.id)} aria-label="Eliminar tarea"><Trash size={17} /></button></motion.div> }
function TaskForm({ close, save, saving }: { close: () => void; save: (data: FormData) => void; saving: boolean }) { const { register, handleSubmit, formState: { errors } } = useForm<FormData>({ defaultValues: { primary: false, note: '' } }); return <div className="overlay" onMouseDown={close}><motion.form initial={{ y: 35 }} animate={{ y: 0 }} className="sheet" onMouseDown={(event) => event.stopPropagation()} onSubmit={handleSubmit(save)}><div className="sheet-head"><div><span className="eyebrow">NUEVA TAREA</span><h2>¿Qué quieres lograr?</h2></div><button type="button" className="icon-button" onClick={close} aria-label="Cerrar"><X size={21} /></button></div><label>Título<input autoFocus {...register('title')} placeholder="Ej. Leer capítulo 3" />{errors.title && <small className="error">{errors.title.message}</small>}</label><label>Nota <span className="optional">OPCIONAL</span><textarea {...register('note')} placeholder="Un poco de contexto…" /></label><label className="primary-toggle"><input type="checkbox" {...register('primary')} /><span className="toggle"><span /></span> Marcar como foco principal</label><button className="primary-button" disabled={saving} type="submit"><Check size={18} /> {saving ? 'Guardando…' : 'Guardar tarea'}</button></motion.form></div> }
function FocusScreen({ task, close, complete }: { task: Task; close: () => void; complete: () => void }) { const [seconds, setSeconds] = useState(1500); const [running, setRunning] = useState(false); useEffect(() => { if (!running) return; const timer = window.setInterval(() => setSeconds((value) => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer) }, [running]); const time = `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`; const finished = seconds === 0; return <motion.div className="focus-screen" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><button className="close-focus" onClick={close} aria-label="Cerrar"><ArrowLeft size={21} /></button><div className="focus-center"><div className="focus-orbit"><div className="focus-core"><Clock size={27} weight="fill" /></div></div><span className="eyebrow">SESIÓN DE CONCENTRACIÓN</span><div className="big-time">{time}</div><p>{task.title}</p></div><div className="focus-panel"><span className="label">BLOQUE 01 · 25 MINUTOS</span><h2>{finished ? 'Buen trabajo. El bloque terminó.' : 'Tu atención es el espacio.'}</h2><div className="focus-actions"><button className="play-focus" onClick={() => finished ? complete() : setRunning(!running)}>{running ? <Pause size={19} weight="fill" /> : <Play size={19} weight="fill" />} {running ? 'Pausar' : finished ? 'Guardar sesión' : 'Comenzar'}</button><button className="finish-focus" onClick={complete}>Terminar</button></div></div></motion.div> }
function BottomNav() { return <nav className="bottom-nav"><a className="active" href="#"><House size={21} weight="fill" /><span>Hoy</span></a><a href="#progress"><TrendUp size={21} /><span>Resumen</span></a></nav> }
