import { useEffect, useState } from 'react'
import { BrowserRouter, Link, useLocation } from 'react-router'
import { Alarm, ArrowLeft, Check, CheckCircle, Clock, Fire, House, ListPlus, Pause, Play, Plus, Trash, TrendUp, X } from '@phosphor-icons/react'
import { AnimatePresence, motion } from 'motion/react'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import { create } from 'zustand'
import './styles.css'

type Task = { id: string; title: string; note?: string; primary: boolean; completed: boolean }
type TaskForm = { title: string; note: string; primary: boolean }
const taskSchema = z.object({ title: z.string().trim().min(2, 'Escribe al menos 2 caracteres'), note: z.string().optional(), primary: z.boolean() })
const starter: Task[] = [
  { id: '1', title: 'Preparar propuesta del proyecto', note: 'Revisar objetivos y próximos pasos', primary: true, completed: false },
  { id: '2', title: 'Responder mensajes pendientes', primary: false, completed: false },
  { id: '3', title: 'Caminar 20 minutos', primary: false, completed: false },
]
const loadTasks = (): Task[] => { try { return JSON.parse(localStorage.getItem('focusflow-tasks') ?? 'null') as Task[] ?? starter } catch { return starter } }
type UiStore = { tasks: Task[]; setTasks: (tasks: Task[]) => void }
const useUiStore = create<UiStore>((set) => ({ tasks: loadTasks(), setTasks: (tasks) => set({ tasks }) }))

export default function App() {
  const { tasks, setTasks } = useUiStore(); const [showForm, setShowForm] = useState(false); const [focusTask, setFocusTask] = useState<Task | null>(null); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(false)
  useEffect(() => localStorage.setItem('focusflow-tasks', JSON.stringify(tasks)), [tasks])
  useEffect(() => { if (!notice) return; const id = window.setTimeout(() => setNotice(''), 2600); return () => window.clearTimeout(id) }, [notice])
  const completed = tasks.filter(t => t.completed).length; const primary = tasks.find(t => t.primary && !t.completed) ?? tasks.find(t => !t.completed); const percent = tasks.length ? Math.round(completed / tasks.length * 100) : 0
  const toggle = (id: string) => { setTasks(tasks.map(t => t.id === id ? { ...t, completed: !t.completed } : t)); setNotice('Tarea actualizada') }
  const remove = (id: string) => { setTasks(tasks.filter(t => t.id !== id)); setNotice('Tarea eliminada') }
  const add = async (data: TaskForm) => { setLoading(true); const parsed = taskSchema.safeParse(data); if (!parsed.success) { setLoading(false); return } const next = { id: crypto.randomUUID(), title: data.title.trim(), note: data.note.trim(), primary: data.primary || tasks.length === 0, completed: false }; setTasks([...tasks.map(t => data.primary ? { ...t, primary: false } : t), next]); setLoading(false); setShowForm(false); setNotice('Tarea creada') }
  return <BrowserRouter><div className="app-shell"><AnimatePresence mode="wait">{focusTask ? <FocusScreen key="focus" task={focusTask} onClose={() => setFocusTask(null)} onComplete={() => { toggle(focusTask.id); setFocusTask(null); setNotice('Sesión completada · +25 min') }} /> : <motion.div key="today" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
    <header className="topbar"><div className="brand-mark">F</div><div><p className="eyebrow">JUEVES · 13 AGO 2026</p><h1>Buenos días, Alex</h1></div><div className="avatar">A</div></header>
    <main className="content"><section className="hello"><div><span className="lime-dot" /> Tu ritmo de hoy</div><p>Un paso enfocado<br /><em>a la vez.</em></p></section>
      <section className="focus-card"><div className="card-top"><span className="label lime-label"><Fire size={15} weight="fill" /> FOCO PRINCIPAL</span><span className="status-dot">● LISTO</span></div><h2>{primary?.title ?? 'Elige una tarea para empezar'}</h2><p className="muted">{primary?.note ?? 'Crea tu primera tarea y haz que el día avance.'}</p><button className="primary-button" onClick={() => primary ? setFocusTask(primary) : setShowForm(true)}><Play size={17} weight="fill" /> Enfocarme 25 min <span>→</span></button></section>
      <section className="timer-strip"><div className="timer-icon"><Clock size={22} /></div><div><strong>Tu próximo bloque</strong><span>25 min de concentración</span></div><span className="ready-pill">POMODORO</span></section>
      <div className="section-heading"><div><span className="eyebrow">LISTA BREVE</span><h3>Tareas de hoy</h3></div><button onClick={() => setShowForm(true)} className="add-link"><Plus size={18} /> Añadir</button></div>
      <section className="task-list">{tasks.length === 0 ? <div className="empty"><ListPlus size={30} /><strong>Tu lista está despejada</strong><span>Añade una tarea para comenzar.</span><button onClick={() => setShowForm(true)}>Crear tarea</button></div> : tasks.map(task => <TaskRow key={task.id} task={task} onToggle={toggle} onRemove={remove} />)}</section>
      <section className="progress-card"><div className="card-top"><div><span className="label">PROGRESO DEL DÍA</span><h3>{percent === 100 ? 'Día completo' : 'Construyendo impulso'}</h3></div><div className="progress-number">{percent}<small>%</small></div></div><div className="progress-track"><motion.div className="progress-fill" animate={{ width: `${percent}%` }} /></div><div className="progress-meta"><span>{completed} de {tasks.length} completadas</span><span><Alarm size={15} /> 0 sesiones</span></div></section>
    </main><BottomNav /></motion.div>}</AnimatePresence>{showForm && <TaskForm loading={loading} onClose={() => setShowForm(false)} onSave={add} />}{notice && <div className="toast" role="status"><CheckCircle size={19} weight="fill" /> {notice}</div>}</div></BrowserRouter>
}
function TaskRow({ task, onToggle, onRemove }: { task: Task; onToggle: (id: string) => void; onRemove: (id: string) => void }) { return <motion.div layout className={`task-row ${task.completed ? 'done' : ''}`}><button className="check" onClick={() => onToggle(task.id)} aria-label={`Completar ${task.title}`}>{task.completed && <Check size={15} weight="bold" />}</button><div className="task-copy"><strong>{task.title}</strong>{task.note && <span>{task.note}</span>}</div>{task.primary && !task.completed && <span className="mini-tag">FOCO</span>}<button className="delete-button" onClick={() => onRemove(task.id)} aria-label="Eliminar tarea"><Trash size={17} /></button></motion.div> }
function TaskForm({ onClose, onSave, loading }: { onClose: () => void; onSave: (data: TaskForm) => void; loading: boolean }) { const { register, handleSubmit, formState: { errors } } = useForm<TaskForm>({ defaultValues: { primary: false } }); return <div className="overlay" onMouseDown={onClose}><motion.form initial={{ y: 35 }} animate={{ y: 0 }} className="sheet" onMouseDown={e => e.stopPropagation()} onSubmit={handleSubmit(onSave)}><div className="sheet-head"><div><span className="eyebrow">NUEVA TAREA</span><h2>¿Qué quieres lograr?</h2></div><button type="button" className="icon-button" onClick={onClose} aria-label="Cerrar"><X size={21} /></button></div><label>Título<input autoFocus {...register('title')} placeholder="Ej. Leer capítulo 3" />{errors.title && <small className="error">{errors.title.message}</small>}</label><label>Nota <span className="optional">OPCIONAL</span><textarea {...register('note')} placeholder="Un poco de contexto…" /></label><label className="primary-toggle"><input type="checkbox" {...register('primary')} /> <span className="toggle"><span /></span> Marcar como foco principal</label><button className="primary-button" disabled={loading} type="submit"><Check size={18} /> {loading ? 'Guardando…' : 'Guardar tarea'}</button></motion.form></div> }
function FocusScreen({ task, onClose, onComplete }: { task: Task; onClose: () => void; onComplete: () => void }) { const [seconds, setSeconds] = useState(1500); const [running, setRunning] = useState(false); useEffect(() => { if (!running) return; const id = window.setInterval(() => setSeconds(s => Math.max(0, s - 1)), 1000); return () => window.clearInterval(id) }, [running]); const time = `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`; const finished = seconds === 0; return <motion.div className="focus-screen" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><button className="close-focus" onClick={onClose} aria-label="Cerrar"><ArrowLeft size={21} /></button><div className="focus-center"><div className="focus-orbit"><div className="focus-core"><Clock size={27} weight="fill" /></div></div><span className="eyebrow">SESIÓN DE CONCENTRACIÓN</span><div className="big-time">{time}</div><p>{task.title}</p></div><div className="focus-panel"><span className="label">BLOQUE 01 · 25 MINUTOS</span><h2>{finished ? 'Buen trabajo. El bloque terminó.' : 'Tu atención es el espacio.'}</h2><div className="focus-actions"><button className="play-focus" onClick={() => finished ? onComplete() : setRunning(!running)}>{running ? <Pause size={19} weight="fill" /> : <Play size={19} weight="fill" />} {running ? 'Pausar' : finished ? 'Guardar sesión' : 'Comenzar'}</button><button className="finish-focus" onClick={onComplete}>Terminar</button></div></div></motion.div> }
function BottomNav() { const location = useLocation(); return <nav className="bottom-nav"><Link className={location.pathname === '/' ? 'active' : ''} to="/"><House size={21} weight="fill" /><span>Hoy</span></Link><Link className={location.pathname === '/progress' ? 'active' : ''} to="/progress"><TrendUp size={21} /><span>Resumen</span></Link></nav> }
